[general]
import = [
    # "./themes/tokyo-night/storm.toml",
    "./themes/nightfox/nordfox.toml",
]

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family =  "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
