require 'init'
-- Function to autoload all config?
-- https://www.reddit.com/r/neovim/comments/reovwj/comment/honjo1t

-- vim.cmd.colorscheme 'generated'
-- vim.cmd [[colorscheme generated]]

-- vim.api.nvim_create_autocmd('BufWritePre', {
--   pattern = { '*.tsx', '*.ts', '*.jsx', '*.vue' },
--   command = 'silent! EslintFixAll',
--   group = vim.api.nvim_create_augroup('MyAutocmdsJavaScripFormatting', {}),
-- })
-- vim.api.nvim_create_user_command('FormatDisable', function(opts)
--   if opts.bang then
--     vim.b.disable_autoformat = true
--   else
--     vim.g.disable_autoformat = true
--   end
--   vim.notify('Autoformat disabled' .. (opts.bang and ' (buffer)' or ' (global)'), vim.log.levels.WARN)
-- end, { desc = 'Disable autoformat-on-save', bang = true })
--
-- vim.api.nvim_create_user_command('FormatEnable', function()
--   vim.b.disable_autoformat = false
--   vim.g.disable_autoformat = false
--   vim.notify('Autoformat enabled', vim.log.levels.INFO)
-- end, { desc = 'Re-enable autoformat-on-save' })
--
-- local auto_format = true
--
-- vim.keymap.set('n', '<leader>uf', function()
--   auto_format = not auto_format
--   if auto_format then
--     vim.cmd 'FormatEnable'
--   else
--     vim.cmd 'FormatDisable'
--   end
-- end, { desc = 'Toggle Autoformat' })
