---
servers:
  hosts:
    play:
      ansible_host: 164.92.183.171
      # ansible_ssh_private_key: ~/.ssh/debian_mate
      ansible_ssh_public_key: ~/.ssh/debian_mate.pub
      ansible_user: artur

    compose:
      ansible_host: 64.226.84.120
      # ansible_ssh_private_key: ~/.ssh/debian_mate
      ansible_ssh_public_key: ~/.ssh/debian_mate.pub
      ansible_user: compose
